deck.js Support for Asciidoc
=============================
:author: Jong Seok Won
:email: <iamtedwon@gmail.com>
:description: All about Apache Kafka.
:revdate: 2018-07-28
:revnumber: 0.9
///////////////////////
	Themes that you can choose includes:
	web-2.0, swiss, neon beamer
///////////////////////
:deckjs_theme: web-2.0
///////////////////////
	Transitions that you can choose includes:
	fade, horizontal-slide, vertical-slide
///////////////////////
:deckjs_transition: horizontal-slide
///////////////////////
	AsciiDoc use `source-highlight` as default highlighter.

	Styles available for pygment highlighter:
	monokai, manni, perldoc, borland, colorful, default, murphy, vs, trac,
	tango, fruity, autumn, bw, emacs, vim, pastie, friendly, native,

	Uncomment following two lines if you want to highlight your code
	with `Pygments`.
///////////////////////
//:pygments:
//:pygments_style: native
///////////////////////
	Uncomment following line if you want to scroll inside slides
	with {down,up} arrow keys.
///////////////////////
//:scrollable:
///////////////////////
	Uncomment following line if you want to link css and js file 
	from outside instead of embedding them into the output file.
///////////////////////
//:linkcss:
///////////////////////
	Uncomment following line if you want to count each incremental
	bullet as a new slide
///////////////////////
//:count_nested:

== Documentation by AsciiDoc

* http://infinispan.org/docs/stable/user_guide/user_guide.html
* http://undertow.io/undertow-docs/undertow-docs-2.0.0/index.html

== AsciiDoc Maven Plugin

* https://github.com/undertow-io/undertow-docs

== AsciiDoc 문법 찾을 때

* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== Example

* /Users/tedwon/.asciidoc/backends/deckjs/example/
